
sudo: false

language: 'php'

php:
  - '5.6'
  - '7.0'

env:
  - COMPOSER_NO_INTERACTION=1 COMPOSER_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - '$HOME/.composer/cache'

install:
  - 'composer install'

script:
  - 'composer run lint'
  - 'composer run test'

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'

notifications:
  email: false
